### ISSUE TITLE
[depoly] : you should deploy this project on GitHub page 

### ISSUE THREAD

**Issue by aaishan-ahmad** [omunite215/FCC-Random-Quote-Generator#2]
Deploy this project on GitHub page and mention link in README.md

**Comment by omunite215** [comment]
> Deploy this project on GitHub page and mention link in README.md
I tried to deploy it on GitHub Pages initially.
I deployed it in Netlify as GitHub Pages didn't rendered Bootstrap correctly.
I found Netlify to be Accurate and Seamless to use.
I have mentioned the link of this project hosted on Netlify.
Thank you for your contribution !!
Looking to collaborate on more projects together.
Thanks!!
